name = "StructArrays"
uuid = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
version = "0.4.0"

[deps]
PooledArrays = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
julia = "1"
PooledArrays = ">=0.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
WeakRefStrings = "ea10d353-3f73-51f8-a26c-33c1cb351aa5"

[targets]
test = ["Test", "OffsetArrays", "Tables", "WeakRefStrings"]
